from kb import KMKKeyboard
from kmk.keys import KC
from kmk.modules.layers import Layers
from kmk.modules.modtap import ModTap
from kmk.hid import HIDModes
from kmk.handlers.sequences import send_string
import supervisor
from kmk.modules.split import Split, SplitSide, SplitType
keyboard = KMKKeyboard()
modtap = ModTap()
layers_ext = Layers()
keyboard.modules.append(layers_ext)
keyboard.modules.append(modtap)
# TODO Comment one of these on each side
#split_side = SplitSide.LEFT
#split_side = SplitSide.RIGHT
split = Split(use_pio=True)
keyboard.modules.append(split)

# keymap
keyboard.keymap = [ [KC.Q,KC.W,KC.E,KC.R,KC.T,KC.Y,KC.U,KC.I,KC.O,KC.P,KC.A,KC.S,KC.D,KC.F,KC.G,KC.H,KC.J,KC.K,KC.L,KC.SCOLON,KC.Z,KC.X,KC.C,KC.V,KC.B,KC.N,KC.M,KC.COMMA,KC.DOT,KC.SLASH,KC.LGUI,KC.BSPC,KC.ENTER,KC.SPACE,KC.NO],
[KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.NO,KC.TRNS,KC.NO,KC.TRNS,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.TRNS,KC.TRNS,KC.PGUP,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.LEFT,KC.UP,KC.DOWN,KC.NO,KC.TRNS,KC.TRNS,KC.LGUI,KC.LALT,KC.MEH,KC.HYPR,KC.TRNS,KC.HOME,KC.NO,KC.END,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.PIPE,KC.NO,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.HASH,KC.NO,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.TRNS,KC.NO,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.NO,KC.AT,KC.TRNS,KC.TRNS,KC.NO,KC.PLUS,KC.NO,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.F7,KC.F8,KC.F9,KC.F10,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.F4,KC.F5,KC.F6,KC.F11,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.F1,KC.F2,KC.F3,KC.F12,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.NO,KC.N7,KC.N8,KC.N9,KC.PLUS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.N0,KC.N1,KC.N2,KC.N3,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.N4,KC.N5,KC.N6,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO],
[KC.TRNS,KC.TRNS,KC.NO,KC.NO,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.TRNS,KC.NO,KC.NO,KC.NO,KC.TRNS,KC.DF(1),KC.LGUI,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.NO,KC.TRNS,KC.DF(0),KC.RALT,KC.NO,KC.TRNS,KC.RESET,KC.TRNS,KC.TAB,KC.TRNS,KC.TRNS,KC.NO],
[KC.NO] ]
# keymap
if __name__ == '__main__':
    keyboard.go(hid_type=HIDModes.USB)
