# auto generated
from kb import KMKKeyboard
from kmk.keys import KC
from kmk.modules.layers import Layers
from kmk.modules.modtap import ModTap
from kmk.hid import HIDModes
from kmk.handlers.sequences import send_string
import supervisor
from kmk.extensions.peg_oled_display import Oled,OledDisplayMode,OledReactionType,OledData
from kmk.extensions.peg_rgb_matrix import Rgb_matrix
from kmk.modules.split import Split,SplitSide,SplitType
keyboard = KMKKeyboard()
modtap = ModTap()
layers_ext = Layers()
keyboard.modules.append(layers_ext)
keyboard.modules.append(modtap)

# keymap
keyboard.keymap = [
[KC.GRV,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.BSPC,KC.TAB,KC.Q,KC.W,KC.E,KC.R,KC.T,KC.Y,KC.U,KC.I,KC.O,KC.P,KC.DEL,KC.ESC,KC.A,KC.S,KC.D,KC.F,KC.G,KC.H,KC.J,KC.K,KC.L,KC.SCLN,KC.QUOT,KC.LSFT,KC.Z,KC.X,KC.C,KC.V,KC.B,KC.N,KC.M,KC.COMM,KC.DOT,KC.SLSH,KC.ENT,KC.PIPE,KC.LCTL,KC.LALT,KC.LGUI,KC.MO(1),KC.SPC,KC.SPC,KC.MO(2),KC.LEFT,KC.DOWN,KC.UP,KC.RGHT],
[KC.ESC,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.UP,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.LEFT,KC.DOWN,KC.RGHT,KC.TRNS,KC.TRNS,KC.CAPS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY],
[KC.GRV,KC.F1,KC.F2,KC.F3,KC.F4,KC.F5,KC.F6,KC.F7,KC.F8,KC.F9,KC.F10,KC.F11,KC.ESC,KC.N1,KC.N2,KC.N3,KC.N4,KC.N5,KC.N6,KC.N7,KC.N8,KC.N9,KC.N0,KC.DEL,KC.TRNS,KC.N4,KC.N5,KC.N6,KC.PLUS,KC.F5,KC.F6,KC.MINS,KC.EQL,KC.LBRC,KC.RBRC,KC.TRNS,KC.ENT,KC.N7,KC.N8,KC.N9,KC.MINS,KC.F11,KC.F12,KC.NUHS,KC.NUBS,KC.MUTE,KC.TRNS,KC.BSLS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.TRNS,KC.MNXT,KC.VOLD,KC.VOLU,KC.MPLY] ]
# keymap

if __name__ == '__main__':
    keyboard.go(hid_type=HIDModes.USB)
